trigger:
  - main

pool:
  vmImage: "ubuntu-latest"

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: "16.x"
    displayName: "setup node@16.x"

  - script: npm setup:ci
    displayName: "npm run setup:ci --if-present"
  - script: npm ci
    displayName: "npm install"
  - script: npm run lint
    displayName: "npm lint"
